config/routes.rb
Rails.application.routes.draw do
  resources :materia
  get 'welcome/tables'
  get 'welcome/diagram'
  get 'error', to: 'error#index'

  resources :rangkings
  resources :kriteria
  resources :alternatifs
  root to: 'welcome#diagram'

end

app/views/layouts/_footer.html.erb
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <b>Version</b> 1.0.0
  </div>
  <strong>&copy; <%= Time.current.year %> Developed by Muhammad Fauzi</strong>
</footer>

app/views/layouts/_header.html.erb
<header class="main-header">
  <!-- Logo -->
  <a href="#" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>💖</b></span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>SPK</b>TOPSIS</span>
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>

    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <span class="hidden-xs">Selamat datang, Visitor :)</span>
          </a>
        </li>
        <li>
          <a href="#"><i class="fa fa-sign-out"></i></a>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_sidebar.html.erb
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">

    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
      <li class="header">MAIN NAVIGATION</li>
      <li class="<%= 'active' if controller?('welcome')%> treeview">
        <a href="#">
          <i class="fa fa-dashboard"></i> <span>Dashboard</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li class="<%= 'active' if controller?('welcome') && action?('diagram')%>"><%= link_to '<i class="fa fa-circle-o"></i>Diagram'.html_safe, root_path %></li>
          <li class="<%= 'active' if controller?('welcome') && action?('tables')%>"><%= link_to '<i class="fa fa-circle-o"></i>Table Analisis'.html_safe, welcome_tables_path %></li>
        </ul>
      </li>

      <li class="<%= 'active' if controller?('alternatifs')%> treeview">
        <a href="#">
          <i class="fa fa-database" aria-hidden="true"></i> <span>Alternatif</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li class="<%= 'active' if controller?('alternatifs') && action?('index', 'edit')%>"><%= link_to '<i class="fa fa-circle-o"></i>List Alternatif'.html_safe, alternatifs_path %></li>
          <li class="<%= 'active' if controller?('alternatifs') && action?('new')%>"><%= link_to '<i class="fa fa-circle-o"></i>Tambah'.html_safe, new_alternatif_path %></li>
        </ul>
      </li>

      <li class="<%= 'active' if controller?('kriteria')%> treeview">
        <a href="#">
          <i class="fa fa-database" aria-hidden="true"></i> <span>Kriteria</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li class="<%= 'active' if controller?('kriteria') && action?('index', 'edit')%>"><%= link_to '<i class="fa fa-circle-o"></i>List Kriteria'.html_safe, kriteria_path %></li>
          <li class="<%= 'active' if controller?('kriteria') && action?('new')%>"><%= link_to '<i class="fa fa-circle-o"></i>Tambah'.html_safe, new_kriterium_path %></li>
        </ul>
      </li>


      <li class="<%= 'active' if controller?('rangkings')%> treeview">
        <a href="#">
          <i class="fa fa-area-chart" aria-hidden="true"></i> <span>Rangking</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li class="<%= 'active' if controller?('rangkings') && action?('index', 'edit')%>"><%= link_to '<i class="fa fa-circle-o"></i>List Rangking'.html_safe, rangkings_path %></li>
          <li class="<%= 'active' if controller?('rangkings') && action?('new')%>"><%= link_to '<i class="fa fa-circle-o"></i>Tambah'.html_safe, new_rangking_path %></li>
        </ul>
      </li>
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'Chart.bundle' %>
    <%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>


  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <style>
    body{
      margin: 0;
    }
  </style>
  <title>💖 SPK Jomber</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
    <div class='clearfix'>
    <%= render 'layouts/header' %>
    <%= render 'layouts/sidebar' %>

    <div class="content-wrapper">
        <%= yield  %>
    </div>

    <%= render 'layouts/footer' %>
  </div>
</div>
  <!-- ./wrapper -->

    <%= javascript_include_tag 'application' %>


  </body>
</html>